// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7rcfyV-RRo3awRfQZcepzWdD2Isrt7JM',
    appId: '1:560350588908:web:fbcdd29ac9baf714e71ac9',
    messagingSenderId: '560350588908',
    projectId: 'mynote-f9459',
    authDomain: 'mynote-f9459.firebaseapp.com',
    storageBucket: 'mynote-f9459.appspot.com',
    measurementId: 'G-STR0T7B3S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkKpz0mxGKykPgkIP1NjDdDclcApQW6WQ',
    appId: '1:560350588908:android:f2e728832253d94de71ac9',
    messagingSenderId: '560350588908',
    projectId: 'mynote-f9459',
    storageBucket: 'mynote-f9459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hB6KNTHXjs5mfmg1VPO0MNOEGnuDap8',
    appId: '1:560350588908:ios:c6db147c9e176dbce71ac9',
    messagingSenderId: '560350588908',
    projectId: 'mynote-f9459',
    storageBucket: 'mynote-f9459.appspot.com',
    iosBundleId: 'com.example.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6hB6KNTHXjs5mfmg1VPO0MNOEGnuDap8',
    appId: '1:560350588908:ios:91f3726311d51a23e71ac9',
    messagingSenderId: '560350588908',
    projectId: 'mynote-f9459',
    storageBucket: 'mynote-f9459.appspot.com',
    iosBundleId: 'com.example.mynote.RunnerTests',
  );
}
